---
- name: tao vlan
  hosts: all
  gather_facts: no

  tasks:
    - name: Create vlan
      ios_vlan:
        vlan_id: "{{ item.number }}"
        name: "{{ item.name }}"
        state: present
      with_items:
        - { number: 50, name: 0 }
        - { number: 51, name: 1 }
        - { number: 52, name: 2 }

    - name: Show vlan
      ios_command:
        commands:
          - show vlan
      register: show_vlan

    - debug: var=show_vlan.stdout_lines
